### ISSUE TITLE
glibc error in dockerized iBEASTIE2 Stan model

### ISSUE THREAD

**Issue by zackgomez** [x811zou/BEASTIE#16]
Command and error
```
# /usr/local/bin/iBEASTIE2
/usr/local/bin/iBEASTIE2: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/local/bin/iBEASTIE2)
```

I fixed a few issues to uncover this one, you can check out a dirty version of the changes in my fork here: https://github.com/zackgomez/BEASTIE

On the first run of the iBEASTIE2 executable libtbb2 was missing which was an easy fix.  This issue with glibc looks to be due to building iBEASTIE2 in a different docker environment based on `gcc:11`.  The running environment is `ubuntu:20.10`.

My guess is the best solution is to build the executable in an ubuntu:20.10 environment as well, but think @tncowart  might know more as the original author of the Dockerfile.

**Comment by zackgomez** [comment]
Perhaps another solution is to downgrade the build container from gcc:11 to gcc:10, which I believe is included in the ubuntu:20.10 image.  I'm trying this now.

**Comment by tncowart** [comment]
Hey @zackgomez,
Thank you for the feedback. I think your suggestion of building the STAN model in an `ubuntu:20.10` environment is a good one. Thank you, I'll make that change soon.

I also want to give you a heads up that there is a PR https://github.com/x811zou/BEASTIE/pull/14 that overlaps with some of the changes you made in your fork. Once the PR is merged in this repo, you'll have some (maybe quite a few) merge conflicts to deal with on your end when you bring in those changes.

**Comment by zackgomez** [comment]
👍
